### ISSUE TITLE
Music addon Player.OnPlay has type "movie"

### ISSUE THREAD

**Issue by bkanuka** [pdf/kodi-callback-daemon#1]
Specifically, playing a song with the Songza Addon triggers the Player.OnPlay actions for the type "movie". I don't know any Go so it's a little hard for me to track down this bug. If the bug isn't on your end could you please point me where to look?

**Comment by pdf** [comment]
We're just working with the type value that's sent to us by Kodi.  I'd guess that the addon is using the default player (I think that's still `DVDPlayer`), rather than the audio player core `PAPlayer`.  I think the only way to fix this would be to change the add-on, because there's no way to identify what caused the item to play from the notification fields according to the API docs.

**Comment by bkanuka** [comment]
hmm, I don't think it's the plugin's issue. It's a Python plugin and this is where songs get added to the playlist (and they are added to the audio playlist):

``` python
 listItem = xbmcgui.ListItem( 
         unicode(next['song']['title']),  
         unicode(next['song']['artist']['name']) 
         ) 
 listItem.setInfo('music',  
         {'duration': next['song']['duration'], 
             'genre': next['song']['genre'], 
             'album': next['song']['album'], 
             'artist': next['song']['artist']['name'], 
             'title': next['song']['title'], 
             'comment': stationName 
         }) 
 listItem.setThumbnailImage(next['song']['cover_url']) 

 # Need to add codec info for XBMC to pick the correct player 
 listItem.addStreamInfo('audio', {'codec': 'mp3'}) 

 url = PLUGIN_URL + 'station=' + str(station) + '&play=' + urllib.quote(next['listen_url']) 
 playlist.add(url, listItem) 
```

So we're totally telling Kodi that this is audio (not movie).

I'll try to look into the library you use to read from Kodi. (I also think it's not your code but was just letting you know where I'm at hunting this down). Thanks!

**Comment by bkanuka** [comment]
You're right - it was a `PAPlayer` issue. Songza plugin sends `.mp4` files, which Kodi uses `DVDPlayer` to use.

**Comment by pdf** [comment]
I did also write the lib, but for a different (unreleased) project, which is why it lives in a different organization.

I feel like this might be a Kodi bug.  I'm pretty certain PAPlayer has support for mp4/m4a, and if you're using PLAYLIST_AUDIO, and setting a type of `music` on the items, you'd think Kodi would at least try to play them with PAPlayer.

**Comment by bkanuka** [comment]
Maybe, maybe not. Kodi assumes mp4 is a video format and therefore might be sending it to DVDPlayer by default. Kodi recommends using the m4a extension for audio only mp4's.

I did force use of PAPlayer but it didn't work. This may be because the audio is actually aac packed in an mp4 and PAPlayer may not have support for aac on Linux. I stopped hunting after this.

FYI: I added a few more debug outputs to your scripts and I can confirm that Kodi is sending the type "movie".

**Comment by pdf** [comment]
Hrm, it must support AAC, since it plays .m4a and .aac files.  If this is just for you (or for debugging), you could add an override in advancedsettings.xml to tell PAPlayer to support .mp4, but if you're looking to make the add-on work consistently that's obviously not an option.  What do the kodi logs say when you try to force PAPlayer?

You shouldn't need any modifications to this code check what Kodi is sending - if you enable debug output in this daemon, it should make the lib output the full contents of requests/replies/notifications.

**Comment by pdf** [comment]
Ah, sorry, I see that notification contents weren't being logged.  Just pushed v1.0.3 to resolve that.
